apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 3fbe52d9b184259f7a8ffe2c9dab1a5432e2c3f9

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
