apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 65eb4b6019da338eae72a5fc9d638c045dfe508f

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
