apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: 52626bb1c8287ea1008f5633c4c90d656b5f8026

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
