apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-dev
  labels:
    app: auth-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api-dev
  template:
    metadata:
      labels:
        app: auth-api-dev
    spec:
      containers:
        - name: auth-api-dev
          image: jifelog-auth-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"