apiVersion: v1
kind: Service
metadata:
  name: auth-api-service-dev
  labels:
    app: auth-api-dev
spec:
  type: ClusterIP
  selector:
    app: auth-api-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
