apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api-ingress
spec:
  ingressClassName: public
  tls:
    - hosts:
        - devuth.jifelog.com
      secretName: tls-secret
  rules:
    - host: devauth.jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-api-service
                port:
                  number: 8080