apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api-ingress
spec:
  ingressClassName: public
  tls:
    - hosts:
        - devauth-api.jifelog.com
      secretName: auth-tls-secret-dev
  rules:
    - host: devauth-api.jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-api-service
                port:
                  number: 8080