apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api-ingress-dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - devauth.jifelog.com
      secretName: tls-secret-dev
  rules:
    - host: devauth.jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-api-service-dev
                port:
                  number: 8080